### ISSUE TITLE
Autosave feature

### ISSUE THREAD

**Issue by flommy** [DoubleDee73/Yass#11]
Would be nice with an autosave feature with configurable intervals.
I believe that it would be practical not to overwrite the txt file, but to create a .bak file or even multiple files (configurable)

**Comment by DoubleDee73** [comment]
This will be released with the 2024.10 release.
The feature is designed to actually do overwrite the txt file, but making a copy of the old version.
The bak-files will be deleted, when switching from the editor back to the library. If there are unsaved changes, and the user chooses to ignore the hint, the changes will be lost along with bak-file.
If Yass crashes for whatever reason, the bak-file will remain in the song directory. Upon reopening Yass and the song, the last-changed-date will be compared. If the bak file appears to be more recent, then the user will have the option to restore the txt.

ping @flommy
