### ISSUE TITLE
Can't Paste Note Heights over multiple lines

### ISSUE THREAD

**Issue by MShayOffice** [DoubleDee73/Yass#17]
After selecting and copying multiple rows of notes, I can't paste the pitches ("heights") onto the same number of notes if they're split across different rows/lines. I'm trying to copy/paste a chorus that repeats with a slight timing difference, but the same number of notes at the same heights.

When I try, it pastes the heights to the first selected line and shows the new tones at the bottom, but doesn't redraw the view with their new positions. If I move the view, then it shows the new positions, but only the first row of note heights gets pasted.

Selected notes copied:
![image](https://github.com/user-attachments/assets/f74807b9-5f2b-419b-b880-f5ee04a4b5ff)

Selected to paste:
![image](https://github.com/user-attachments/assets/196f2081-2baa-410a-a02b-4fc7110dda6b)

After notes are pasted:
![image](https://github.com/user-attachments/assets/1fe1173c-237c-4082-854c-71010d42c995)

After moving the view:
![image](https://github.com/user-attachments/assets/ab976256-af08-4e40-9d09-465e4556f4d0)

The other Paste options don't seem to have a problem doing so over multiple selected lines.

[Edit: This should probably be another ticket, but the "Paste Note Heights" option also doesn't seem to add to the Undo stack. When I hit Undo, it reverses any "Paste Note Heights" actions I've done in a row, and then undoes whatever was done before that.]

**Comment by DoubleDee73** [comment]
@MShayOffice I will have a look. In the meantime, have you tried to just select the first note rather than all the notes you want to paste the melody over?
Basically:
1. Select the melody
2. Copy
3. Select the first note from where the melody to be pasted should start
4. Paste

**Comment by MShayOffice** [comment]
Seems good! Thank you!
